import { IQuestion } from "../types";

export const questions: IQuestion[] = [
  {
    id: "1",
    question: "What is the capital of France?",
    answers: ["Paris", "London", "Rome", "Berlin"],
    correctAnswer: "Paris",
  },
  {
    id: "2",
    question: "Which planet is known as the Red Planet?",
    answers: ["Earth", "Venus", "Mars", "Jupiter"],
    correctAnswer: "Mars",
  },
  {
    id: "3",
    question: "What is the largest ocean on Earth?",
    answers: ["Atlantic", "Indian", "Pacific", "Arctic"],
    correctAnswer: "Pacific",
  },
  {
    id: "4",
    question: "Who wrote 'Hamlet'?",
    answers: ["Shakespeare", "Hemingway", "Tolkien", "Dickens"],
    correctAnswer: "Shakespeare",
  },
  {
    id: "5",
    question: "Which element has the chemical symbol 'O'?",
    answers: ["Oxygen", "Osmium", "Oxide", "Oganesson"],
    correctAnswer: "Oxygen",
  },
  {
    id: "6",
    question: "What is the square root of 64?",
    answers: ["6", "7", "8", "9"],
    correctAnswer: "8",
  },
  {
    id: "7",
    question: "In which year did the Titanic sink?",
    answers: ["1905", "1912", "1920", "1930"],
    correctAnswer: "1912",
  },
  {
    id: "8",
    question: "Which country is home to the kangaroo?",
    answers: ["India", "Australia", "South Africa", "Brazil"],
    correctAnswer: "Australia",
  },
  {
    id: "9",
    question: "What is the hardest natural substance on Earth?",
    answers: ["Gold", "Iron", "Diamond", "Platinum"],
    correctAnswer: "Diamond",
  },
  {
    id: "10",
    question: "Which famous scientist developed the theory of relativity?",
    answers: ["Newton", "Einstein", "Tesla", "Bohr"],
    correctAnswer: "Einstein",
  },
  {
    id: "11",
    question: "What is the longest river in the world?",
    answers: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctAnswer: "Nile",
  },
  {
    id: "12",
    question: "Which is the smallest country in the world?",
    answers: ["Monaco", "Vatican City", "Liechtenstein", "Malta"],
    correctAnswer: "Vatican City",
  },
  {
    id: "13",
    question: "Who painted the Mona Lisa?",
    answers: ["Picasso", "Da Vinci", "Van Gogh", "Rembrandt"],
    correctAnswer: "Da Vinci",
  },
  {
    id: "14",
    question: "What is the capital of Japan?",
    answers: ["Beijing", "Seoul", "Bangkok", "Tokyo"],
    correctAnswer: "Tokyo",
  },
  {
    id: "15",
    question: "What is the largest planet in our solar system?",
    answers: ["Mars", "Jupiter", "Saturn", "Neptune"],
    correctAnswer: "Jupiter",
  },
  {
    id: "16",
    question: "Who discovered penicillin?",
    answers: ["Fleming", "Pasteur", "Curie", "Edison"],
    correctAnswer: "Fleming",
  },
  {
    id: "17",
    question: "Which sport is known as the 'king of sports'?",
    answers: ["Cricket", "Basketball", "Football", "Tennis"],
    correctAnswer: "Football",
  },
  {
    id: "18",
    question: "What is the chemical symbol for gold?",
    answers: ["Ag", "Au", "Pb", "Fe"],
    correctAnswer: "Au",
  },
  {
    id: "19",
    question: "Which city hosted the 2016 Summer Olympics?",
    answers: ["London", "Beijing", "Tokyo", "Rio de Janeiro"],
    correctAnswer: "Rio de Janeiro",
  },
  {
    id: "20",
    question: "How many continents are there?",
    answers: ["5", "6", "7", "8"],
    correctAnswer: "7",
  },
  {
    id: "21",
    question: "Who was the first man to walk on the moon?",
    answers: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "John Glenn"],
    correctAnswer: "Neil Armstrong",
  },
  {
    id: "22",
    question: "Which gas do plants absorb from the atmosphere?",
    answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
    correctAnswer: "Carbon Dioxide",
  },
  {
    id: "23",
    question: "What is the smallest unit of life?",
    answers: ["Organ", "Tissue", "Cell", "Molecule"],
    correctAnswer: "Cell",
  },
  {
    id: "24",
    question: "Who wrote 'Pride and Prejudice'?",
    answers: ["Emily Brontë", "Jane Austen", "Charles Dickens", "Mark Twain"],
    correctAnswer: "Jane Austen",
  },
  {
    id: "25",
    question: "What is the largest mammal?",
    answers: ["Elephant", "Giraffe", "Blue Whale", "Shark"],
    correctAnswer: "Blue Whale",
  },
  {
    id: "26",
    question: "Which element is needed for the production of nuclear energy?",
    answers: ["Helium", "Uranium", "Carbon", "Nitrogen"],
    correctAnswer: "Uranium",
  },
  {
    id: "27",
    question: "Which country is famous for inventing pizza?",
    answers: ["France", "Italy", "Greece", "Mexico"],
    correctAnswer: "Italy",
  },
  {
    id: "28",
    question: "What is the speed of light?",
    answers: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
    correctAnswer: "300,000 km/s",
  },
  {
    id: "29",
    question: "Which is the highest mountain in the world?",
    answers: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"],
    correctAnswer: "Mount Everest",
  },
  {
    id: "30",
    question: "Who was the first president of the United States?",
    answers: [
      "George Washington",
      "Abraham Lincoln",
      "John Adams",
      "Thomas Jefferson",
    ],
    correctAnswer: "George Washington",
  },
];
